[tool.poetry]
name = "progmaticlab-task"
version = "0.1.0"
description = ""
authors = ["Dmitrii Samsonenko <samsondm97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
